### ISSUE TITLE
[RFE] Support fot ESP8266

### ISSUE THREAD

**Issue by 3PO** [stevemarple/AS3935#2] opened 2018-04-23 17:01 UTC
It it possible to add support for the ESP8266?

When i compile the AS3935_demo.ino, i  get the following error:

    D:\Users\3PO\Documents\Arduino\libraries\SoftWire\src\SoftWire.cpp:1:25: fatal error: util/atomic.h: No such file or directory
    
     #include <util/atomic.h>
    
                             ^
    
    compilation terminated.
    
    exit status 1
    Fehler beim Kompilieren für das Board NodeMCU 1.0 (ESP-12E Module)
Thanks in advance. :)

**Comment by stevemarple** [comment] 2018-04-23 20:52
This is a `SoftWire` problem and appears to be a duplicate of the issue reported in https://github.com/stevemarple/SoftWire/issues/5.
If you have a ESP8266 replacement for the AVR construct `ATOMIC_BLOCK` then I can add support for the ESP8266. Unfortunately the Arduino library only has functions to enable and disable interrupts, with nothing to read back the whether interrupts are enabled.

**Comment by 3PO** [comment] 2018-04-25 17:24
Does this mean, that the AS3935 will never work with the ESP8266?

**Comment by stevemarple** [comment] 2018-04-25 18:56
I've altered the `SoftWire` library so that `ATOMIC_BLOCK` is used only for AVR architectures, although this brings a small risk of spurious signals on the I2C bus. You may see occasional I2C corruption but I think it is likely that v1.1.0 of `SoftWire` will work for you.

**Closed as completed by stevemarple** 2018-04-25 18:56 UTC

**Comment by 3PO** [comment] 2018-04-26 15:36
Thx.

Now it seems working. ;)

But there is an other Problem in the AS3935_demo.ino:

    D:\Users\3PO\Downloads\ESP8266\AS3935\AS3935_demo.ino\AS3935_demo.ino: In function 'void readRegs(uint8_t, uint8_t)':
    
    AS3935_demo.ino:36: error: 'EIFR' was not declared in this scope
    
       Serial.println(EIFR, HEX);
    
                      ^
    
    exit status 1
    'EIFR' was not declared in this scope
